spring:
  application.name: Hello
  flyway.locations: classpath:db/migration
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbsyncdata
    username: ${POSTGRES_USERNAME:dbsyncdata}
    password: ${POSTGRES_PASSWORD:dbsyncdata}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
## IDAM feign connection
idam:
  api:
    url: ${IDAM_URL:http://127.0.0.1:5000}
    client-id: ${OAUTH2_CLIENT_ID:rd-professional-api}
    redirect-uri: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect}
    authorization: ${OAUTH2_AUTH:ZWRtaW4ucmVmZGF0YUBobWN0cy5uZXQ6Q2hhbjllLW1lCCo=}
    client-authorization: ${OAUTH2_CLIENT_AUTH:ymQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2PA==}

  s2s-auth:
    totp_secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: rd_profile_sync
    url: ${S2S_URL:http://127.0.0.1:8990}
  s2s-authorised:
    services: ${SYNC_S2S_AUTHORISED_SERVICES:rd_professional_api}

scheduler:
  config: ${CRON_SCHEDULE:0 0 */1 * * *}

exui.role:
  hmcts-admin: prd-admin
  pui-user-manager: pui-user-manager
  pui-organisation-manager: pui-organisation-manager
  pui-finance-manager: pui-finance-manager
  pui-case-manager: pui-case-manager

## user profile feign connection
userprofile.api.url: ${USER_PROFILE_URL:http://127.0.0.1:8091}

loggingComponentName: RD_Profile_Sync