spring:
  application.name: Hello
  flyway.locations: classpath:db/migration

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbsyncdata
    username: ${POSTGRES_USERNAME:dbsyncdata}
    password: ${POSTGRES_PASSWORD:dbsyncdata}

security:
  authorisedServices:
    - "it"
## IDAM feign connection
idam:
  s2s-auth:
    url: ${S2S_URL:http://127.0.0.1:8990}
    totp_secret: ${S2S_SECRET:K6KA6PRLRFWQLSD6}
    microservice: rd_professional_api
  api:
    url: ${IDAM_URL:http://127.0.0.1:5000}
## IDAM feign connection
auth:
  idam:
    client:
      baseUrl: ${IDAM_URL:http://127.0.0.1:5000}
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://127.0.0.1:8990}

exui.role:
  hmcts-admin: prd-admin
  pui-user-manager: pui-user-manager
  pui-organisation-manager: pui-organisation-manager
  pui-finance-manager: pui-finance-manager
  pui-case-manager: pui-case-manager

## user profile feign connection
userprofile.api.url: ${USER_PROFILE_URL:http://127.0.0.1:8091}
